version: '3.3'
services:

  mysql-server:
    container_name: int221-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: kaofood
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
        - int221-network

  frontend:
    container_name: int221-node.js
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: always
    command: npm run serve
    networks:
      - int221-network
    
  backend:
    container_name: int221-spring
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    restart: always
    networks:
        - int221-network

networks:
    int221-network:
        driver: bridge